version: '3'
services:
  projeto_dakee:
    build:
      context: . 
      dockerfile: dockerfile
    command: uvicorn database.main:api --reload --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - .:/workspace:rw
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3305:3305
    environment:
      MYSQL_DATABASE: dakee_db
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
  adminer:
    image: adminer
    ports:
      - 8080:8080